org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

kotlin.incremental=true
kotlin.daemon.jvm.options=-Xmx2g -XX:+UseParallelGC
kotlin.build.report.output=file
kotlin.build.report.file.output_dir=build/reports/kotlin-build
ksp.incremental=true
ksp.incremental.intermodule=true
