package at.hannibal2.skyhanni.config.features.gui.customscoreboard

import at.hannibal2.skyhanni.data.DateFormat

// Kept so other mods can migrate this config to themselves
enum class ScoreboardConfigElement(val displayName: String) {
    TITLE("§6§lSKYBLOCK"),
    PROFILE("§7♲ Ironman"),
    PURSE("Purse: §652,763,737"),
    MOTES("Motes: §d64,647"),
    BANK("Bank: §6249M"),
    BITS("Bits: §b59,264"),
    COPPER("Copper: §c23,495"),
    SOWDUST("Sowdust: §23,210,307"),
    GEMS("Gems: §a57,873"),
    HEAT("Heat: §c♨ 14"),
    COLD("Cold: §b0❄"),
    NORTH_STARS("North Stars: §d756"),
    CHUNKED_STATS("§652,763,737 §7| §d64,647 §7| §6249M\n§b59,264 §7| §c23,495 §7| §23,210,307"),
    SOULFLOW("Soulflow: §3761"),
    ISLAND("§7㋖ §aHub"),
    LOCATION("§7⏣ §bVillage"),
    PLAYER_AMOUNT("§7Players: §a69§7/§a80"),
    VISITING(" §a✌ §7(§a1§7/6)"),
    DATE("Late Summer 11th"),
    TIME("§710:40pm §b☽"),
    LOBBY_CODE("§7${DateFormat.US_SLASH_MMDDYYYY} §8mega77CK"),
    POWER("Power: §aSighted §7(§61.263§7)"),
    TUNING("Tuning: §c❁34§7, §e⚔20§7, and §9☣7"),
    COOKIE("§dCookie Buff§f: 3d 17h"),
    OBJECTIVE("Objective:\n§eStar SkyHanni on Github"),
    SLAYER("Slayer Quest\n §7- §cVoidgloom Seraph III\n §7- §e12§7/§c120 §7Kills"),
    QUIVER("Flint Arrow: §f1,234"),
    POWDER("§9§lPowder\n §7- §fMithril: §254,646\n §7- §fGemstone: §d51,234\n §7- §fGlacite: §b86,574"),
    SKYBLOCK_XP("SB Level: 287\nXP: §b26§3/§b100"),
    EVENTS("§7Wide Range of Events\n§7(too much to show all)"),
    MAYOR("§2Diana §7(§e4d 12h§7)\n §7- §eLucky!\n §7- §eMythological Ritual\n §7- §ePet XP Buff"),
    PARTY("§9§lParty (4):\n §7- §fhannibal2\n §7- §fMoulberry\n §7- §fEmpa_\n §7- §fSkirtwearer"),
    FOOTER("§ewww.hypixel.net"),
    EXTRA("§cUnknown lines the mod is not detecting"),
    EMPTY_LINE("----- Separator -----"),
    EMPTY_LINE2("----- Separator -----"),
    EMPTY_LINE3("----- Separator -----"),
    EMPTY_LINE4("----- Separator -----"),
    EMPTY_LINE5("----- Separator -----"),
    EMPTY_LINE6("----- Separator -----"),
    EMPTY_LINE7("----- Separator -----"),
    EMPTY_LINE8("----- Separator -----"),
    EMPTY_LINE9("----- Separator -----"),
    EMPTY_LINE10("----- Separator -----"),
    EMPTY_LINE11("----- Separator -----"),
    EMPTY_LINE12("----- Separator -----"),
    EMPTY_LINE13("----- Separator -----"),
    EMPTY_LINE14("----- Separator -----"),
    EMPTY_LINE15("----- Separator -----"),
    ;

    override fun toString(): String = displayName

    companion object {
        @Suppress("StorageNeedsExpose")
        @JvmField
        val defaultOptions = listOf(
            TITLE,
            LOBBY_CODE,
            EMPTY_LINE,
            DATE,
            TIME,
            ISLAND,
            PLAYER_AMOUNT,
            LOCATION,
            VISITING,
            PROFILE,
            EMPTY_LINE2,
            PURSE,
            MOTES,
            BANK,
            BITS,
            COPPER,
            SOWDUST,
            GEMS,
            HEAT,
            COLD,
            NORTH_STARS,
            SOULFLOW,
            EMPTY_LINE3,
            EVENTS,
            COOKIE,
            QUIVER,
            POWER,
            TUNING,
            EMPTY_LINE4,
            OBJECTIVE,
            SLAYER,
            POWDER,
            MAYOR,
            PARTY,
            FOOTER,
            EXTRA,
        )
    }
}
