package at.hannibal2.skyhanni.dungeon.damageindicator

enum class BossType {
    DUNGEON,

//    CRIMSON_AILE_BLADESOUL,
    NETHER_BLADESOUL,
    NETHER_MAGMA_BOSS,
    NETHER_ASHFANG,
    NETHER_BARBARIAN_DUKE,
    NETHER_MAGE_OUTLAW,

    NETHER_VANQUISHER,

    END_OBSIDIAN_DEFENDER,
    END_ENDERMAN_SLAYER,
    END_ENDER_DRAGON,

}