package at.hannibal2.skyhanni.api.event

import at.hannibal2.skyhanni.SkyHanniMod.launch
import at.hannibal2.skyhanni.events.utils.InitFinishedEvent
import at.hannibal2.skyhanni.skyhannimodule.SkyHanniModule
import at.hannibal2.skyhanni.test.command.ErrorManager
import at.hannibal2.skyhanni.utils.coroutines.CoroutineSettings
import org.objectweb.asm.ClassReader
import org.objectweb.asm.Type
import org.objectweb.asm.tree.ClassNode
import java.nio.file.Files
import java.nio.file.Path
import kotlin.time.Duration

/**
 * Verifies that no `@HandleEvent` function is declared outside a `@SkyHanniModule` class.
 *
 * [SkyHanniEvents.register] only reads `declaredMethods` of the module objects listed in `LoadedModules`, so a
 * handler declared anywhere else is never registered and is silently dead code. `ModuleProcessor` rejects this at
 * compile time; this scan is an independent second line of defense that also covers classes never passed to
 * [SkyHanniEvents.register] at all, which the check in `SkyHanniEvents.getEventData` cannot see.
 *
 * Both annotations are retained at runtime, so this reads module membership straight out of the bytecode. It
 * deliberately does not consult `LoadedModules`, which is itself generated by the processor being double-checked.
 *
 * The class files are read with ASM instead of reflection so that a stray handler is found without loading its
 * class, which would run static initializers outside their intended lifecycle.
 */
@SkyHanniModule(devOnly = true)
object HandleEventModuleValidator {

    private const val PACKAGE_PATH = "at/hannibal2/skyhanni"

    private const val MAX_REPORTED = 10

    private val parseFlags = ClassReader.SKIP_CODE or ClassReader.SKIP_DEBUG or ClassReader.SKIP_FRAMES

    private val handleEventDescriptor = Type.getDescriptor(HandleEvent::class.java)
    private val moduleDescriptor = Type.getDescriptor(SkyHanniModule::class.java)

    private val settings = CoroutineSettings("@HandleEvent module validation", Duration.INFINITE).withIOContext()

    @HandleEvent
    fun onInitFinished(event: InitFinishedEvent) {
        settings.launch { validate() }
    }

    private fun validate() {
        val strays = sourceRoots().flatMap { root ->
            Files.walk(root).use { paths ->
                paths.iterator().asSequence()
                    .filter { it.toString().endsWith(".class") }
                    .mapNotNull { strayHandlerOwnerOf(it) }
                    .toList()
            }
        }.distinct().sorted()
        if (strays.isEmpty()) return

        val shown = strays.take(MAX_REPORTED).joinToString()
        val omitted = strays.size - MAX_REPORTED
        ErrorManager.crashInDevEnv(
            "${strays.size} class(es) declare @HandleEvent functions but are not annotated with @SkyHanniModule, " +
                "so those functions are never registered: $shown" +
                if (omitted > 0) " (and $omitted more)" else "",
        )
    }

    /**
     * Returns the directories holding SkyHanni's own compiled classes.
     *
     * The mod container's root paths are not usable here: in a development environment Loom reports only
     * `build/resources/main`, which contains no class files at all. The class loader instead resolves the package
     * to every output directory that actually holds it, which is one per compiled language.
     */
    private fun sourceRoots(): List<Path> =
        javaClass.classLoader.getResources(PACKAGE_PATH).toList()
            .filter { it.protocol == "file" }
            .map { Path.of(it.toURI()) }

    /**
     * Returns the binary name of the class at [path] if it declares an `@HandleEvent` function
     * but is not itself annotated with `@SkyHanniModule`.
     */
    private fun strayHandlerOwnerOf(path: Path): String? {
        val node = ClassNode()
        try {
            Files.newInputStream(path).use { ClassReader(it).accept(node, parseFlags) }
        } catch (_: Exception) {
            return null
        }
        if (node.visibleAnnotations.orEmpty().any { it.desc == moduleDescriptor }) return null
        val declaresHandler = node.methods.orEmpty().any { method ->
            method.visibleAnnotations.orEmpty().any { it.desc == handleEventDescriptor }
        }
        return node.name.replace('/', '.').takeIf { declaresHandler }
    }
}
