package at.hannibal2.skyhanni.features.garden.fortuneguide

enum class FarmingItems {
    WHEAT, CARROT, POTATO, CANE, NETHER_WART, PUMPKIN, MELON, COCOA_BEANS, SUGAR_CANE, CACTUS, MUSHROOM, OTHER_BOOTS,
    HELMET, CHESTPLATE, LEGGINGS, BOOTS, NECKLACE, CLOAK, BELT, BRACELET, ELEPHANT, MOOSHROOM_COW, RABBIT
}