package at.hannibal2.skyhanni.features.garden.fortuneguide

enum class FFTypes {
    TOTAL, BASE, REFORGE, ABILITY, GREEN_THUMB, BASE_FF, ANITA, FARMING_LVL, COMMUNITY_SHOP, PLOTS,
    CAKE, PET_ITEM, COUNTER, COLLECTION, TURBO, DEDICATION, SUNDER, HARVESTING, CULTIVATING, FFD,
    CROP_UPGRADE, ACCESSORY
}