package at.hannibal2.skyhanni.damageindicator

enum class BossType {
    DUNGEON,

//    CRIMSON_AILE_BLADESOUL,
    NETHER_BLADESOUL,
    NETHER_MAGMA_BOSS,
    NETHER_ASHFANG,
    NETHER_BARBARIAN_DUKE,
    NETHER_MAGE_OUTLAW,

    NETHER_VANQUISHER,

    END_ENDSTONE_PROTECTOR,
    END_ENDERMAN_SLAYER,
    END_ENDER_DRAGON,

    HUB_REVENANT_HORROR,
    HUB_HEADLESS_HORSEMAN,

}