name: 'Setup Java, Gradle and check out the source code'

runs:
    using: composite
    steps:
        -   name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
                distribution: 'temurin'
                java-version: 21
                cache: gradle
        -   name: Setup gradle
            uses: gradle/actions/setup-gradle@v4
