name: Build

on:
    push:
        branches:
            - "*"
        paths-ignore:
            - ".gitignore"
    pull_request_target:
        branches:
            - "*"
        paths-ignore:
            - ".gitignore"
    workflow_dispatch:
permissions: write-all
jobs:
    build_1_8_9:
        name: "Build 1.8.9"
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.ref }}
                    repository: ${{ github.event.pull_request.head.repo.full_name }}

            -   name: Setup workspace
                uses: ./.github/actions/setup-normal-workspace

            -   name: Enable preprocessor
                run: |
                    mkdir -p .gradle
                    echo skyhanni.multi-version=compile > .gradle/private.properties

            -   name: Cache build output
                uses: actions/cache@v4
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Build with Gradle w/ retry
                uses: ./.github/actions/gradle-retry
                with:
                    gradle-command: 1.8.9:build --no-daemon --stacktrace -PskipDetekt=true

            -   name: Upload 1.8.9 build
                uses: actions/upload-artifact@v4
                if: ${{ !cancelled() }}
                with:
                    name: "1.8.9 Development Build"
                    path: build/libs/*.jar

    build_1_21_5:
        name: "Build 1.21.5"
        runs-on: ubuntu-latest
        needs: build_1_8_9
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.ref }}
                    repository: ${{ github.event.pull_request.head.repo.full_name }}

            -   name: Setup workspace
                uses: ./.github/actions/setup-normal-workspace

            -   name: Enable preprocessor
                run: |
                    mkdir -p .gradle
                    echo skyhanni.multi-version=compile > .gradle/private.properties

            -   name: Cache build output
                uses: actions/cache@v4
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Build with Gradle w/ retry
                uses: ./.github/actions/gradle-retry
                with:
                    gradle-command: 1.21.5:build --no-daemon --stacktrace -PskipDetekt=true

            -   name: Upload 1.21.5 build
                uses: actions/upload-artifact@v4
                if: ${{ !cancelled() }}
                with:
                    name: "1.21.5 Development Build"
                    path: build/libs/*.jar

    build_1_21_7:
        name: "Build 1.21.7"
        runs-on: ubuntu-latest
        needs: build_1_21_5
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.ref }}
                    repository: ${{ github.event.pull_request.head.repo.full_name }}

            -   name: Setup workspace
                uses: ./.github/actions/setup-normal-workspace

            -   name: Enable preprocessor
                run: |
                    mkdir -p .gradle
                    echo skyhanni.multi-version=compile > .gradle/private.properties

            -   name: Cache build output
                uses: actions/cache@v4
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-


            -   name: Build with Gradle w/ retry
                uses: ./.github/actions/gradle-retry
                with:
                    gradle-command: 1.21.7:build --no-daemon --stacktrace -PskipDetekt=true

            -   name: Upload 1.21.7 build
                uses: actions/upload-artifact@v4
                if: ${{ !cancelled() }}
                with:
                    name: "1.21.7 Development Build"
                    path: build/libs/*.jar

