name: Run detekt on push

on:
    workflow_run:
        workflows: ["Build"]
        types: [completed]
        branches:
            - "beta"
jobs:
    detekt:
        name: Run detekt
        runs-on: ubuntu-latest
        if: |
            github.event.workflow_run.event == 'push' &&
            github.event.workflow_run.conclusion == 'success'
        permissions:
            contents: read
        steps:
            -   name: Checkout code
                uses: actions/checkout@v6
                with:
                    ref: ${{ github.event.workflow_run.head_sha }}
            -   uses: ./.github/actions/setup-normal-workspace
            -   name: Run detekt main (w/ typing analysis) w/gradle retry
                uses: ./.github/actions/gradle-retry
                with:
                    gradle-command: detektMain --stacktrace
            -   name: Check if SARIF file exists
                id: check_sarif
                run: |
                    if [ -f "build/reports/detekt/main.sarif" ]; then
                        echo "exists=true" >> $GITHUB_OUTPUT
                    else
                        echo "exists=false" >> $GITHUB_OUTPUT
                    fi
            -   name: Annotate detekt failures
                if: ${{ !cancelled() && steps.check_sarif.outputs.exists == 'true' }}
                run: |
                    chmod +x .github/scripts/process_detekt_sarif.sh
                    ./.github/scripts/process_detekt_sarif.sh build/reports/detekt/main.sarif
