name: Detekt

on:
    pull_request:
        branches:
            - "*"
    workflow_dispatch:

jobs:
    detekt:
        name: Run detekt
        runs-on: ubuntu-latest
        outputs:
            sarif_exists: ${{ steps.check_sarif.outputs.exists }}
            detekt_failed: ${{ steps.run_detekt.outcome == 'failure' }}
        steps:
            - name: Checkout PR code
              uses: actions/checkout@v4

            - uses: ./.github/actions/setup-normal-workspace

            - name: Run detekt main (w/ typing analysis) w/gradle retry
              id: run_detekt
              uses: ./.github/actions/gradle-retry
              continue-on-error: true
              with:
                  gradle-command: detektMain --stacktrace

            - name: Check if SARIF file exists
              id: check_sarif
              if: always()
              run: |
                  if [ -f "versions/1.8.9/build/reports/detekt/main.sarif" ]; then
                      echo "exists=true" >> $GITHUB_OUTPUT
                  else
                      echo "exists=false" >> $GITHUB_OUTPUT
                  fi

            - name: Annotate detekt failures
              if: ${{ !cancelled() && steps.check_sarif.outputs.exists == 'true' }}
              run: |
                  chmod +x .github/scripts/process_detekt_sarif.sh
                  ./.github/scripts/process_detekt_sarif.sh versions/1.8.9/build/reports/detekt/main.sarif | tee detekt_output.txt

            # Step 4: Upload the processed comment text as an artifact for the next workflow
            - name: Upload detekt output as artifact
              if: ${{ !cancelled() && steps.check_sarif.outputs.exists == 'true' }}
              uses: actions/upload-artifact@v4
              with:
                  name: detekt-output
                  path: detekt_output.txt
