# https://github.com/marketplace/actions/label-remover

name: "Remove All Labels"

on:
    pull_request_target:
        types: [closed]

jobs:
    remove_very_soon:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: rogerluan/label-remover@v1.0.1
              with:
                  github_token: ${{ secrets.github_token }}
